CREATE TABLE GW_RPTS_GTT
(
  GW_RPTS_GTT_SEQUENCE DECIMAL(28) NOT NULL,
  GW_RPTS_GTT_OBJECT_NAME VARCHAR(120) NOT NULL,
  GW_RPTS_GTT_SID VARCHAR(8),
  GW_RPTS_GTT_MIME VARCHAR(4),
  GW_RPTS_GTT_CREATE_DATE DATETIME NOT NULL,
  GW_RPTS_GTT_TIMES_ACCESSED INT,
  GW_RPTS_GTT_LAST_ACCESSED DATETIME,
  GW_RPTS_GTT_JOB_PARAMETERS VARCHAR(200),
  GW_RPTS_GTT_BLOB LONGBLOB
);