CREATE TABLE GW_RPTS
(
  GW_RPTS_SEQUENCE NUMBER(28) PRIMARY KEY NOT NULL,
  GW_RPTS_OBJECT_NAME VARCHAR2(120) NOT NULL,
  GW_RPTS_SID VARCHAR2(8),
  GW_RPTS_MIME VARCHAR2(4),
  GW_RPTS_CREATE_DATE DATE NOT NULL,
  GW_RPTS_TIMES_ACCESSED NUMBER(7),
  GW_RPTS_LAST_ACCESSED DATE,
  GW_RPTS_JOB_PARAMETERS VARCHAR2(200),
  GW_RPTS_BLOB BLOB
);
CREATE INDEX GW_RPTS_OBJECT_SID_IDX ON GW_RPTS (GW_RPTS_OBJECT_NAME, GW_RPTS_SID);
CREATE INDEX GW_RPTS_OBJECT_DATE_IDX ON GW_RPTS (GW_RPTS_OBJECT_NAME, GW_RPTS_CREATE_DATE);
CREATE INDEX GW_RPTS_OBJECT_IDX ON GW_RPTS (GW_RPTS_OBJECT_NAME);