CREATE TABLE GW_RPTS_GTT
(
  GW_RPTS_GTT_SEQUENCE NUMBER(28) NOT NULL,
  GW_RPTS_GTT_OBJECT_NAME VARCHAR2(120) NOT NULL,
  GW_RPTS_GTT_SID VARCHAR2(8),
  GW_RPTS_GTT_MIME VARCHAR2(4),
  GW_RPTS_GTT_CREATE_DATE DATE NOT NULL,
  GW_RPTS_GTT_TIMES_ACCESSED NUMBER(7),
  GW_RPTS_GTT_LAST_ACCESSED DATE,
  GW_RPTS_GTT_JOB_PARAMETERS VARCHAR2(200),
  GW_RPTS_GTT_BLOB BLOB
);