--------------------------------------------------------
--  File created - Wednesday-March-22-2017   
--------------------------------------------------------
-- Unable to render TABLE DDL for object ERPTS.GW_RPTS_DEF with DBMS_METADATA attempting internal generator.
CREATE TABLE ERPTS.GW_RPTS_DEF 
(
  GW_RPTS_DEF_OBJECT_NAME VARCHAR2(120 CHAR) NOT NULL 
, GW_RPTS_DEF_OBJECT_DESC VARCHAR2(300 CHAR) 
, GW_RPTS_DEF_MAINTAINED_DEPT VARCHAR2(30 CHAR) 
, GW_RPTS_DEF_MAINTAINED_COLL VARCHAR2(2 CHAR) 
, GW_RPTS_DEF_RETENTION_DAYS NUMBER(6, 0) 
, GW_RPTS_DEF_USERID VARCHAR2(30 CHAR) 
, GW_RPTS_DEF_ACTIVITY_DATE DATE 
) 
LOGGING 
TABLESPACE DEVELOPMENT 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELCREATE INDEX ERPTS.GW_RPTS_DEF_OBJECT_DESC_IDX ON ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_DESC ASC) 
LOGGING 
TABLESPACE INDX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
CREATE UNIQUE INDEX ERPTS.GW_RPTS_DEF_PK ON ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME ASC) 
LOGGING 
TABLESPACE DEVELOPMENT 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELALTER TABLE ERPTS.GW_RPTS_DEF
ADD CONSTRAINT GW_RPTS_DEF_PK PRIMARY KEY 
(
  GW_RPTS_DEF_OBJECT_NAME 
)
USING INDEX GW_RPTS_DEF_PK
ENABLE
-- Unable to render INDEX DDL for object ERPTS.GW_RPTS_DEF_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX ERPTS.GW_RPTS_DEF_PK ON ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME ASC) 
LOGGING 
TABLESPACE DEVELOPMENT 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
-- Unable to render INDEX DDL for object ERPTS.GW_RPTS_DEF_OBJECT_DESC_IDX with DBMS_METADATA attempting internal generator.
CREATE INDEX ERPTS.GW_RPTS_DEF_OBJECT_DESC_IDX ON ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_DESC ASC) 
LOGGING 
TABLESPACE INDX 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
