--------------------------------------------------------
--  File created - Wednesday-March-22-2017   
--------------------------------------------------------
-- Unable to render TABLE DDL for object ERPTS.GW_RPTS_DEF with DBMS_METADATA attempting internal generator.
CREATE TABLE ERPTS.GW_RPTS_DEF 
(
  GW_RPTS_DEF_OBJECT_NAME VARCHAR2(120 CHAR) NOT NULL 
, GW_RPTS_DEF_OBJECT_DESC VARCHAR2(300 CHAR) 
, GW_RPTS_DEF_MAINTAINED_DEPT VARCHAR2(30 CHAR) 
, GW_RPTS_DEF_MAINTAINED_COLL VARCHAR2(2 CHAR) 
, GW_RPTS_DEF_RETENTION_DAYS NUMBER(6, 0) 
, GW_RPTS_DEF_USERID VARCHAR2(30 CHAR) 
, GW_RPTS_DEF_ACTIVITY_DATE DATE 
) 

REM INSERTING into ERPTS.GW_RPTS_DEF
SET DEFINE OFF;
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('SARETMT','saretmt',null,null,30,null,to_date('29-NOV-16','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('SMPCPRG','smpcprg',null,null,30,null,to_date('13-JAN-17','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('PWS_ALAMO_RPT.CSV','pws_alamo_rpt.csv',null,null,30,null,to_date('03-MAR-17','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('TSRCBIL','tsrcbil',null,null,30,null,to_date('17-NOV-16','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('SARBDSN','sarbdsn',null,null,30,null,to_date('27-JAN-17','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('GURPDED','gurpded',null,null,30,null,to_date('22-NOV-16','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('SORCPLN','sorcpln',null,null,30,null,to_date('20-DEC-16','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('TGPHOLD','tgphold',null,null,30,null,to_date('04-JAN-17','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('TGPHOLD_2','tgphold_2',null,null,30,null,to_date('17-JAN-17','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('TGRCLOS','tgrclos',null,null,30,null,to_date('13-FEB-17','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('SRTPURG','srtpurg',null,null,30,null,to_date('13-FEB-17','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('SEC_ARGOS_TK_TEST.CSV',null,null,null,30,null,to_date('08-MAR-17','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('UC4_VALUE_SEARCH_TEST',null,null,null,30,null,to_date('22-MAR-17','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('SRTLOAD','srtload',null,null,30,null,to_date('03-FEB-17','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('TESTEPRINT.TXT','testeprint.txt',null,null,30,null,to_date('03-MAR-17','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('GURPDED.PDF',null,null,null,30,null,to_date('08-MAR-17','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('TSRSBIL',null,null,null,30,null,to_date('21-MAR-17','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('GE_SEC_ARGOS_TK_TEST','ge_sec_argos_tk_test',null,null,30,null,to_date('22-NOV-16','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('GZRTCCV','gzrtccv',null,null,30,null,to_date('30-NOV-16','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('SURLOAD','surload',null,null,30,null,to_date('02-DEC-16','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('TGRFEED','tgrfeed',null,null,30,null,to_date('07-DEC-16','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('SHRCGPA','shrcgpa',null,null,30,null,to_date('09-JAN-17','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('SURDELT','surdelt',null,null,30,null,to_date('11-JAN-17','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('SFRPINI','sfrpini',null,null,30,null,to_date('13-JAN-17','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('SZR189U','szr189u',null,null,30,null,to_date('18-JAN-17','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('TSRRFND','tsrrfnd',null,null,30,null,to_date('13-FEB-17','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('PWT_005_A4_EXEMPT_LOAD.LIS',null,null,null,30,null,to_date('08-MAR-17','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('SRRSRIN',null,null,null,30,null,to_date('10-MAR-17','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('PWS_HISTORY_HONORS','pws_history_honors',null,null,30,null,to_date('17-NOV-16','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('SFRFEES','sfrfees',null,null,30,null,to_date('03-FEB-17','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('SHRASTD','shrastd',null,null,30,null,to_date('13-JAN-17','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('TGRAPPL','tgrappl',null,null,30,null,to_date('10-FEB-17','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('TVRCRED','tvrcred',null,null,30,null,to_date('14-FEB-17','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('SIS_USER_INFO.CSV','sis_user_info.csv',null,null,30,null,to_date('07-MAR-17','DD-MON-RR'));
Insert into ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME,GW_RPTS_DEF_OBJECT_DESC,GW_RPTS_DEF_MAINTAINED_DEPT,GW_RPTS_DEF_MAINTAINED_COLL,GW_RPTS_DEF_RETENTION_DAYS,GW_RPTS_DEF_USERID,GW_RPTS_DEF_ACTIVITY_DATE) values ('UC4_VALUE_SEARCH',null,null,null,30,null,to_date('14-MAR-17','DD-MON-RR'));
-- Unable to render INDEX DDL for object ERPTS.GW_RPTS_DEF_PK with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX ERPTS.GW_RPTS_DEF_PK ON ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_NAME ASC) 
-- Unable to render INDEX DDL for object ERPTS.GW_RPTS_DEF_OBJECT_DESC_IDX with DBMS_METADATA attempting internal generator.
CREATE INDEX ERPTS.GW_RPTS_DEF_OBJECT_DESC_IDX ON ERPTS.GW_RPTS_DEF (GW_RPTS_DEF_OBJECT_DESC ASC) 

