CREATE TABLE GW_RPTS_DEF
(
  GW_RPTS_DEF_OBJECT_NAME VARCHAR(120) PRIMARY KEY NOT NULL,
  GW_RPTS_DEF_OBJECT_DESC VARCHAR(300),
  GW_RPTS_DEF_MAINTAINED_DEPT VARCHAR(30),
  GW_RPTS_DEF_MAINTAINED_COLL VARCHAR(2),
  GW_RPTS_DEF_RETENTION_DAYS INT,
  GW_RPTS_DEF_USERID VARCHAR(30),
  GW_RPTS_DEF_ACTIVITY_DATE DATETIME
);